### ISSUE TITLE
Issue getting package to work

### ISSUE THREAD

**Issue by nicer00ster** [transitive-bullshit/react-particle-effect-button#2]
I've set up a new environment with create-react-app and added this as a dependency. Using the following code in my App.js doesn't seem to do anything other than add the text "BUTTON CONTENT GOES HERE"
 ```
<ParticleEffectButton
          color='palegreen'
          hidden={this.state.hidden}
          style='fill'
          children={'hey'}
        >
          <button>HEY</button>
        </ParticleEffectButton>
```

Am I missing something? I have it imported and React is up to date.

**Comment by nicer00ster** [comment]
Nevermind I figured it out lol. My bad.

**Comment by THamza** [comment]
@nicer00ster How did you manage to make it work please?
